apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: iqacf32fz-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/iqacf32fz-java-springboot-gitops